FROM ubuntu:5001/nginx:latest

MAINTAINER Jon Roquelaure jonathanr@jfrog.com

RUN /bin/bash -c cd ~; cd /home ; mkdir -p exec
ADD jdk/jdk-8u111-linux-x64.tar.gz /home/exec
RUN /bin/bash -c cd /home/exec; mv /home/exec/jdk* /home/exec/jdk8
ENV JAVA_HOME=/home/exec/jdk8
ENV PATH=$PATH:/home/exec/jdk8/bin

CMD service nginx  start && /bin/bash
