node() {
    stage 'Build base image'
        git url: 'https://github.com/jroquelaure/docker-lifecycle.git', branch: 'master'
        def server = Artifactory.server('yodafrog')
        def downloadSpec = """{
            "files": [
            {
                "pattern": "generic-local/*jdk*.tar.gz",
                "target": "docker-framework/jdk/",
                "flat": "true"
            }
        ]
        }"""
        def buildInfo = server.download(downloadSpec)
        docker.build("yodafrog.sas.jfrog.internal:5001/docker-framework:$buildInfo.number", "-f docker-framework/DockerFile ./docker-framework/") 
       
    stage "Push built image"
        def artDocker= Artifactory.docker('jenkins', 'AKCp2VouvByHfvNzqdwsgqKU7o9HneAXZwjWaHAgm9YCemnWXgu23GMR9JjnTtCu7Rue8PmTw')
        def dockerInfo = artDocker.push("yodafrog.sas.jfrog.internal:5001/docker-framework:$buildInfo.number", 'docker-dev-local')
        buildInfo.append(dockerInfo)
        server.publishBuildInfo(buildInfo)
    
    stage "Xray scan"
        def xrayConfig = [
        //Mandatory parameters
        'buildName'         : buildInfo.name,
        'buildNumber'       : buildInfo.number,

        //Optional
        'failBuild'        :true //Default
        ]

    // Scan xray build
    def xrayResults = server.xrayScan xrayConfig
    // Print full report from xray
    echo xrayResults as String

    if (currentBuild.result == null) {
        stage "Test image"    
            //TODO
        
        stage "Promote build"
            def promotionConfig = [
            // Mandatory parameters
            'buildName'          : buildInfo.name,
            'buildNumber'        : buildInfo.number,
            'targetRepo'         : 'docker-prod-local2',

            // Optional parameters
            'comment'            : 'ready for release',
            'sourceRepo'         : 'docker-dev-local',
            'status'             : 'Released',
            'includeDependencies': false,
            'copy'               : true
        ]

        // Promote build
        server.promote promotionConfig
        
        sh("""curl -H 'X-JFrog-Art-Api:AKCp2VouvByHfvNzqdwsgqKU7o9HneAXZwjWaHAgm9YCemnWXgu23GMR9JjnTtCu7Rue8PmTw' http://yodafrog.sas.jfrog.internal/artifactory/api/docker/docker-prod-local2/v2/promote -H "Content-Type:application/json" -d '{"targetRepo" : "docker-prod-local2", "dockerRepository" : "docker-framework", "tag" : "$buildInfo.number", "targetTag" : "latest", "copy": true }' """)
    }
}